import { useState } from 'react';
import Sidebar from './components/Sidebar';
import Header from './components/Header';
import Dashboard from './components/Dashboard';
import Arena from './components/Arena';
import Locker from './components/Locker';
import Profile from './components/Profile';
import CaseDossierModal from './components/CaseDossierModal';
import NewCaseModal from './components/NewCaseModal';
import { casesData } from './data/cases';
import { Case, RecentCase, UserProgress } from './types';
import { Sparkles, Linkedin, CheckCircle, X } from 'lucide-react';

export default function App() {
  const [currentView, setCurrentView] = useState<string>('despacho');
  const [cases, setCases] = useState<Case[]>(casesData);
  const [searchTerm, setSearchTerm] = useState<string>('');
  
  // Initialize user progress exactly as pictured in the dashboard image
  const [userProgress, setUserProgress] = useState<UserProgress>({
    name: 'Carlos',
    plan: 'Premium Plan',
    litigationScore: 78,
    efficacy: 85,
    legalTech: 72,
    oratory: 60,
    casesCompleted: 2,
    recentScores: [
      { date: '15 Jun', score: 60, caseTitle: 'Prueba Inicial' },
      { date: '28 Jun', score: 68, caseTitle: 'Daños y Perjuicios #12' },
      { date: '30 Jun', score: 92, caseTitle: 'Robo Agravado #45' }
    ]
  });

  // Recent cases list matching the cards in the image
  const [recentCases, setRecentCases] = useState<RecentCase[]>([
    {
      id: 'robo-agravado',
      title: 'Robo Agravado #45',
      score: 92,
      stars: 3,
      status: 'Absolución',
      date: 'FINALIZADO AYER',
      type: 'Penal'
    },
    {
      id: 'danos-perjuicios',
      title: 'Daños y Perjuicios #12',
      score: 68,
      stars: 2,
      status: 'Apelación',
      date: 'HACE 3 DÍAS',
      type: 'Civil'
    }
  ]);

  // Modal control states
  const [selectedCaseForDossier, setSelectedCaseForDossier] = useState<Case | null>(null);
  const [showNewCaseModal, setShowNewCaseModal] = useState<boolean>(false);
  const [activeCaseId, setActiveCaseId] = useState<string | null>(null);

  // Elegant Toast state for success messages
  const [toast, setToast] = useState<{ visible: boolean; message: string; type: 'success' | 'linkedin' } | null>(null);

  const showToast = (message: string, type: 'success' | 'linkedin' = 'success') => {
    setToast({ visible: true, message, type });
    setTimeout(() => {
      setToast(null);
    }, 4500);
  };

  // Search filter handler
  const filteredCases = cases.filter(c => 
    c.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
    c.type.toLowerCase().includes(searchTerm.toLowerCase()) ||
    c.skill.toLowerCase().includes(searchTerm.toLowerCase())
  );

  // Handle case selection from Dashboard cards/quick actions
  const handleSelectCase = (caseId: string, action: 'study' | 'arena') => {
    const selected = cases.find(c => c.id === caseId);
    if (!selected) return;

    if (action === 'study') {
      setSelectedCaseForDossier(selected);
    } else {
      setActiveCaseId(caseId);
      setCurrentView('arena');
    }
  };

  // Custom Case Generated by IA Wizard
  const handleCaseGenerated = (newCase: Case) => {
    setCases([newCase, ...cases]);
    showToast(`¡Caso "${newCase.title}" generado exitosamente por el Motor IA!`, 'success');
    // Open Dossier study modal immediately for the new case
    setSelectedCaseForDossier(newCase);
  };

  // Handle completed court simulation game
  const handleSimulationComplete = (
    score: number,
    status: 'Absolución' | 'Condena' | 'Apelación',
    efficacy: number,
    legalTech: number,
    oratory: number,
    caseId: string
  ) => {
    const originCase = cases.find(c => c.id === caseId) || cases[0];
    
    // Create new recent case record
    const newRecord: RecentCase = {
      id: `rc-${Date.now()}`,
      title: originCase.title,
      score,
      stars: score >= 85 ? 3 : score >= 65 ? 2 : 1,
      status,
      date: 'HOY',
      type: originCase.type
    };

    // Calculate updated metrics dynamically based on weighting
    const updatedEfficacy = Math.round((userProgress.efficacy + efficacy) / 2);
    const updatedLegalTech = Math.round((userProgress.legalTech + legalTech) / 2);
    const updatedOratory = Math.round((userProgress.oratory + oratory) / 2);
    const updatedGlobalScore = Math.round((updatedEfficacy + updatedLegalTech + updatedOratory) / 3);

    // Update state
    setRecentCases([newRecord, ...recentCases]);
    setUserProgress({
      ...userProgress,
      casesCompleted: userProgress.casesCompleted + 1,
      efficacy: updatedEfficacy,
      legalTech: updatedLegalTech,
      oratory: updatedOratory,
      litigationScore: updatedGlobalScore,
      recentScores: [
        ...userProgress.recentScores,
        { date: 'Hoy', score, caseTitle: originCase.title }
      ]
    });

    // Go back to Despacho or Locker
    setCurrentView('despacho');
    showToast(`¡Simulación guardada! Score obtenido: ${score}/100 (${status}).`, 'success');
  };

  // Share certificate logic
  const handleShareCertificate = (caseTitle: string) => {
    showToast(`¡Certificado del caso "${caseTitle}" preparado para compartir! Copiado al portapapeles.`, 'linkedin');
  };

  // View technical feedback
  const handleViewFeedback = (caseId: string) => {
    setCurrentView('locker');
    showToast('Redirigido al Locker de Resultados para ver retroalimentación técnica.', 'success');
  };

  // Update profile metrics
  const handleUpdateProgress = (updates: Partial<UserProgress>) => {
    setUserProgress(prev => ({ ...prev, ...updates }));
  };

  return (
    <div id="applet-viewport" className="flex bg-[#F8FAFC] min-h-screen text-gray-800">
      
      {/* Interactive Left Sidebar */}
      <Sidebar 
        currentView={currentView}
        onViewChange={(view) => {
          setCurrentView(view);
          setActiveCaseId(null); // Reset preselected case
        }}
        onOpenNewCase={() => setShowNewCaseModal(true)}
        userProgress={userProgress}
      />

      {/* Main View Container */}
      <div className="flex-1 flex flex-col min-w-0 min-h-screen overflow-x-hidden">
        
        {/* Top Header Panel */}
        <Header 
          userProgress={userProgress}
          onOpenNewCase={() => setShowNewCaseModal(true)}
          onSearch={(term) => setSearchTerm(term)}
          onViewChange={(view) => setCurrentView(view)}
        />

        {/* Scrollable View Area */}
        <main className="flex-grow px-8 py-6 overflow-y-auto max-w-7xl mx-auto w-full">
          
          {/* View Routing Engine */}
          {currentView === 'despacho' && (
            <Dashboard 
              cases={filteredCases}
              recentCases={recentCases}
              userProgress={userProgress}
              onSelectCase={handleSelectCase}
              onViewChange={setCurrentView}
              onShareCertificate={handleShareCertificate}
              onViewFeedback={handleViewFeedback}
            />
          )}

          {currentView === 'arena' && (
            <Arena 
              cases={cases}
              activeCaseId={activeCaseId}
              onBackToDashboard={() => setCurrentView('despacho')}
              onSimulationComplete={handleSimulationComplete}
            />
          )}

          {currentView === 'locker' && (
            <Locker 
              userProgress={userProgress}
              recentCases={recentCases}
              onShareCertificate={handleShareCertificate}
            />
          )}

          {currentView === 'perfil' && (
            <Profile 
              userProgress={userProgress}
              onUpdateProgress={handleUpdateProgress}
            />
          )}

        </main>
      </div>

      {/* Interactive Dossier study modal */}
      {selectedCaseForDossier && (
        <CaseDossierModal 
          caseItem={selectedCaseForDossier}
          onClose={() => setSelectedCaseForDossier(null)}
          onEnterArena={(caseId) => handleSelectCase(caseId, 'arena')}
        />
      )}

      {/* New custom case creator modal */}
      {showNewCaseModal && (
        <NewCaseModal 
          onClose={() => setShowNewCaseModal(false)}
          onCaseGenerated={handleCaseGenerated}
        />
      )}

      {/* Dynamic Floating Toast Notifications */}
      {toast && (
        <div 
          id="toast-notification"
          className={`fixed bottom-6 right-6 z-50 p-4 rounded-2xl shadow-xl border flex items-start space-x-3 max-w-sm animate-bounce duration-300 ${
            toast.type === 'linkedin' 
              ? 'bg-[#0077B5] border-[#005B8C] text-white' 
              : 'bg-emerald-600 border-emerald-700 text-white'
          }`}
        >
          {toast.type === 'linkedin' ? (
            <Linkedin className="w-5 h-5 shrink-0 mt-0.5 fill-white stroke-none" />
          ) : (
            <CheckCircle className="w-5 h-5 shrink-0 mt-0.5 text-white" />
          )}
          <div className="flex-grow">
            <h5 className="font-bold text-xs">
              {toast.type === 'linkedin' ? 'LinkedIn Share' : 'Acción Confirmada'}
            </h5>
            <p className="text-[11px] font-medium leading-normal opacity-90 mt-0.5">{toast.message}</p>
          </div>
          <button 
            onClick={() => setToast(null)}
            className="text-white/70 hover:text-white shrink-0"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      )}

    </div>
  );
}
