import { useRef, useState } from 'react';
import Sidebar from './components/Sidebar';
import Header from './components/Header';
import Dashboard from './components/Dashboard';
import Arena from './components/Arena';
import Locker from './components/Locker';
import Profile from './components/Profile';
import CaseDossierModal from './components/CaseDossierModal';
import NewCaseModal from './components/NewCaseModal';
import { casesData } from './data/cases';
import { Case, RecentCase, UserProgress } from './types';
import { Sparkles, Linkedin, CheckCircle, X, AlertTriangle } from 'lucide-react';
import { useModalA11y } from './hooks/useModalA11y';

export default function App() {
  const [currentView, setCurrentView] = useState<string>('despacho');
  const [cases, setCases] = useState<Case[]>(casesData);

  // Initialize user progress exactly as pictured in the dashboard image
  const [userProgress, setUserProgress] = useState<UserProgress>({
    name: 'Carlos',
    plan: 'Premium Plan',
    litigationScore: 78,
    efficacy: 85,
    legalTech: 72,
    oratory: 60,
    casesCompleted: 2,
    recentScores: [
      { date: '15 Jun', score: 60, caseTitle: 'Prueba Inicial' },
      { date: '28 Jun', score: 68, caseTitle: 'Daños y Perjuicios #12' },
      { date: '30 Jun', score: 92, caseTitle: 'Robo Agravado #45' }
    ]
  });

  // Recent cases list matching the cards in the image
  const [recentCases, setRecentCases] = useState<RecentCase[]>([
    {
      id: 'robo-agravado',
      title: 'Robo Agravado #45',
      score: 92,
      stars: 3,
      status: 'Absolución',
      date: 'FINALIZADO AYER',
      type: 'Penal'
    },
    {
      id: 'danos-perjuicios',
      title: 'Daños y Perjuicios #12',
      score: 68,
      stars: 2,
      status: 'Apelación',
      date: 'HACE 3 DÍAS',
      type: 'Civil'
    }
  ]);

  // Modal control states
  const [selectedCaseForDossier, setSelectedCaseForDossier] = useState<Case | null>(null);
  const [showNewCaseModal, setShowNewCaseModal] = useState<boolean>(false);
  const [activeCaseId, setActiveCaseId] = useState<string | null>(null);

  // Tracks whether there's a simulation in progress in La Arena, to warn before leaving it
  const [simulationActive, setSimulationActive] = useState(false);
  const [pendingView, setPendingView] = useState<string | null>(null);

  // Navigation is intercepted while a simulation is active, so the user gets a chance to confirm
  const requestViewChange = (view: string) => {
    if (view === currentView) return;
    if (currentView === 'arena' && simulationActive) {
      setPendingView(view);
      return;
    }
    setCurrentView(view);
    setActiveCaseId(null);
  };

  const confirmLeaveSimulation = () => {
    const view = pendingView;
    setPendingView(null);
    if (view) {
      setCurrentView(view);
      setActiveCaseId(null);
    }
  };

  // Elegant Toast state for success messages
  const [toast, setToast] = useState<{ visible: boolean; message: string; type: 'success' | 'linkedin' } | null>(null);
  const [toastClosing, setToastClosing] = useState(false);
  const toastTimers = useRef<{ hide?: ReturnType<typeof setTimeout>; remove?: ReturnType<typeof setTimeout> }>({});

  const dismissToast = () => {
    clearTimeout(toastTimers.current.hide);
    clearTimeout(toastTimers.current.remove);
    setToastClosing(true);
    toastTimers.current.remove = setTimeout(() => {
      setToast(null);
      setToastClosing(false);
    }, 250);
  };

  const showToast = (message: string, type: 'success' | 'linkedin' = 'success') => {
    clearTimeout(toastTimers.current.hide);
    clearTimeout(toastTimers.current.remove);
    setToastClosing(false);
    setToast({ visible: true, message, type });
    toastTimers.current.hide = setTimeout(dismissToast, 4200);
  };

  // Handle case selection from Dashboard cards/quick actions
  const handleSelectCase = (caseId: string, action: 'study' | 'arena') => {
    const selected = cases.find(c => c.id === caseId);
    if (!selected) return;

    if (action === 'study') {
      setSelectedCaseForDossier(selected);
    } else {
      setActiveCaseId(caseId);
      setCurrentView('arena');
    }
  };

  // Custom Case Generated by IA Wizard
  const handleCaseGenerated = (newCase: Case) => {
    setCases([newCase, ...cases]);
    showToast(`¡Caso "${newCase.title}" generado exitosamente por el Motor IA!`, 'success');
    // Open Dossier study modal immediately for the new case
    setSelectedCaseForDossier(newCase);
  };

  // Handle completed court simulation game
  const handleSimulationComplete = (
    score: number,
    status: 'Absolución' | 'Condena' | 'Apelación',
    efficacy: number,
    legalTech: number,
    oratory: number,
    caseId: string
  ) => {
    const originCase = cases.find(c => c.id === caseId) || cases[0];
    
    // Create new recent case record
    const newRecord: RecentCase = {
      id: `rc-${Date.now()}`,
      title: originCase.title,
      score,
      stars: score >= 85 ? 3 : score >= 65 ? 2 : 1,
      status,
      date: 'HOY',
      type: originCase.type
    };

    // Calculate updated metrics dynamically based on weighting
    const updatedEfficacy = Math.round((userProgress.efficacy + efficacy) / 2);
    const updatedLegalTech = Math.round((userProgress.legalTech + legalTech) / 2);
    const updatedOratory = Math.round((userProgress.oratory + oratory) / 2);
    const updatedGlobalScore = Math.round((updatedEfficacy + updatedLegalTech + updatedOratory) / 3);

    // Update state
    setRecentCases([newRecord, ...recentCases]);
    setUserProgress({
      ...userProgress,
      casesCompleted: userProgress.casesCompleted + 1,
      efficacy: updatedEfficacy,
      legalTech: updatedLegalTech,
      oratory: updatedOratory,
      litigationScore: updatedGlobalScore,
      recentScores: [
        ...userProgress.recentScores,
        { date: 'Hoy', score, caseTitle: originCase.title }
      ]
    });

    // Go back to Despacho or Locker
    setCurrentView('despacho');
    showToast(`¡Simulación guardada! Score obtenido: ${score}/100 (${status}).`, 'success');
  };

  // Share certificate logic
  const handleShareCertificate = (caseTitle: string) => {
    showToast(`¡Certificado del caso "${caseTitle}" preparado para compartir! Copiado al portapapeles.`, 'linkedin');
  };

  // View technical feedback
  const handleViewFeedback = (caseId: string) => {
    setCurrentView('locker');
    showToast('Redirigido al Locker de Resultados para ver retroalimentación técnica.', 'success');
  };

  // Update profile metrics
  const handleUpdateProgress = (updates: Partial<UserProgress>) => {
    setUserProgress(prev => ({ ...prev, ...updates }));
  };

  return (
    <div id="applet-viewport" className="flex flex-col md:flex-row bg-[#F8FAFC] min-h-screen text-gray-800">
      
      {/* Interactive Left Sidebar */}
      <Sidebar
        currentView={currentView}
        onViewChange={requestViewChange}
        onOpenNewCase={() => setShowNewCaseModal(true)}
        userProgress={userProgress}
      />

      {/* Main View Container */}
      <div className="flex-1 flex flex-col min-w-0 min-h-screen overflow-x-hidden mb-24 md:mb-0">
        
        {/* Top Header Panel */}
        <Header
          userProgress={userProgress}
          onOpenNewCase={() => setShowNewCaseModal(true)}
          onViewChange={requestViewChange}
        />

        {/* Scrollable View Area */}
        <main className="flex-grow px-4 sm:px-8 py-6 overflow-y-auto w-full">
          
          {/* View Routing Engine */}
          {currentView === 'despacho' && (
            <Dashboard 
              cases={cases}
              recentCases={recentCases}
              userProgress={userProgress}
              onSelectCase={handleSelectCase}
              onViewChange={setCurrentView}
              onShareCertificate={handleShareCertificate}
              onViewFeedback={handleViewFeedback}
            />
          )}

          {currentView === 'arena' && (
            <Arena
              cases={cases}
              activeCaseId={activeCaseId}
              onBackToDashboard={() => requestViewChange('despacho')}
              onSimulationComplete={handleSimulationComplete}
              onSimulationActiveChange={setSimulationActive}
            />
          )}

          {currentView === 'locker' && (
            <Locker 
              userProgress={userProgress}
              recentCases={recentCases}
              onShareCertificate={handleShareCertificate}
            />
          )}

          {currentView === 'perfil' && (
            <Profile 
              userProgress={userProgress}
              onUpdateProgress={handleUpdateProgress}
            />
          )}

        </main>
      </div>

      {/* Interactive Dossier study modal */}
      {selectedCaseForDossier && (
        <CaseDossierModal 
          caseItem={selectedCaseForDossier}
          onClose={() => setSelectedCaseForDossier(null)}
          onEnterArena={(caseId) => handleSelectCase(caseId, 'arena')}
        />
      )}

      {/* New custom case creator modal */}
      {showNewCaseModal && (
        <NewCaseModal
          onClose={() => setShowNewCaseModal(false)}
          onCaseGenerated={handleCaseGenerated}
        />
      )}

      {/* Confirmation before abandoning a simulation in progress */}
      {pendingView && (
        <LeaveSimulationModal
          onCancel={() => setPendingView(null)}
          onConfirm={confirmLeaveSimulation}
        />
      )}

      {/* Dynamic Floating Toast Notifications */}
      {toast && (
        <div
          id="toast-notification"
          className={`fixed bottom-6 right-6 z-50 p-4 rounded-2xl shadow-xl border flex items-start space-x-3 max-w-sm duration-300 ${
            toastClosing ? 'animate-out fade-out slide-out-to-right-4' : 'animate-in fade-in slide-in-from-right-4'
          } ${
            toast.type === 'linkedin'
              ? 'bg-[#0077B5] border-[#005B8C] text-white'
              : 'bg-emerald-600 border-emerald-700 text-white'
          }`}
        >
          {toast.type === 'linkedin' ? (
            <Linkedin className="w-5 h-5 shrink-0 mt-0.5 fill-white stroke-none" />
          ) : (
            <CheckCircle className="w-5 h-5 shrink-0 mt-0.5 text-white" />
          )}
          <div className="flex-grow">
            <h5 className="font-bold text-xs">
              {toast.type === 'linkedin' ? 'LinkedIn Share' : 'Acción Confirmada'}
            </h5>
            <p className="text-[11px] font-medium leading-normal opacity-90 mt-0.5">{toast.message}</p>
          </div>
          <button
            onClick={dismissToast}
            className="text-white/70 hover:text-white shrink-0"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      )}

    </div>
  );
}

interface LeaveSimulationModalProps {
  onCancel: () => void;
  onConfirm: () => void;
}

function LeaveSimulationModal({ onCancel, onConfirm }: LeaveSimulationModalProps) {
  const [isClosing, setIsClosing] = useState(false);

  // Play the exit animation before actually resolving the user's choice
  const close = (after: () => void) => {
    setIsClosing(true);
    setTimeout(after, 180);
  };

  const containerRef = useModalA11y<HTMLDivElement>(() => close(onCancel));

  return (
    <div className={`fixed inset-0 bg-black/60 z-[60] flex items-center justify-center p-4 backdrop-blur-sm ${isClosing ? 'animate-out fade-out duration-200' : 'animate-in fade-in duration-200'}`}>
      <div
        ref={containerRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby="leave-sim-modal-title"
        className={`bg-white rounded-3xl max-w-sm w-full p-6 space-y-5 shadow-2xl ${isClosing ? 'animate-out fade-out zoom-out-95 duration-200' : 'animate-in fade-in zoom-in-95 duration-200'}`}
      >
        <div className="flex items-center space-x-2.5 text-amber-600">
          <AlertTriangle className="w-6 h-6 shrink-0" />
          <h5 id="leave-sim-modal-title" className="font-sans font-black text-base text-gray-900">¿Salir de la simulación?</h5>
        </div>

        <p className="text-xs text-gray-500 leading-relaxed font-medium">
          Tienes un juicio en curso en La Arena. Si sales ahora, perderás el progreso de esta sesión de litigio.
        </p>

        <div className="flex justify-end space-x-3 pt-2 border-t border-gray-100">
          <button
            id="btn-leave-sim-cancel"
            onClick={() => close(onCancel)}
            className="px-4 py-2.5 rounded-xl border border-gray-300 hover:bg-gray-100 text-xs font-bold text-gray-700 transition-colors"
          >
            Continuar Litigando
          </button>

          <button
            id="btn-leave-sim-confirm"
            onClick={() => close(onConfirm)}
            className="px-4 py-2.5 rounded-xl bg-red-600 hover:bg-red-700 text-white text-xs font-bold transition-colors shadow"
          >
            Salir de todos modos
          </button>
        </div>
      </div>
    </div>
  );
}
